### ISSUE TITLE
Image names in mac osx infrastructure

### ISSUE THREAD

**Issue by amanya** [travis-ci/worker#324]
We are providing image names through
env vars, so we have in `IMAGE_ALIASES` the value `default,xcode8_3` and
then we define `IMAGE_ALIAS_DEFAULT` as `test` and `IMAGE_ALIAS_XCODE8_3`
as `xcode8.3` (this is how the image is called in vsphere).

We start a project with `osx_image: xcode8.3` in the .travis.yml and
the alias it picks is always the default one, I'm getting that in the
worker logs:

`time="2017-06-19T10:08:36Z" level=info msg="selected image name"
dist=precise group=stable image_name=test job=355 language=swift
os=osx osx_image=xcode8.3 pid=28516
processor=b26790ac-e82f-4c48-b079-2001081a4b96
repository="albert-manya/simple-project"`

Should the image alias be encoded in a specific way?

**Comment by meatballhat** [comment]
@amanya Hello!  I realize this code hasn't changed in quite awhile, but can you post what version of worker you're using?

**Comment by amanya** [comment]
@meatballhat v2.5.0

I just saw that this name is created in https://github.com/travis-ci/worker/blob/master/image/env_selector.go, I'm trying to understand the logic behind it.

For the log I pasted I get: `osx_image_xcode8.3_dist_precise_group_stable_swift`

**Comment by meatballhat** [comment]
@amanya Cool, thank you!  Do you get the same results on latest release?  v2.9.2

**Comment by amanya** [comment]
I tested it and I can confirm now that the above format worked in v2.5.0.

We don't use newer versions than v2.5.0 because I think it is not suitable for using in with enterprise version, or there are some news on that?

**Comment by meatballhat** [comment]
@amanya I would like to know about what's not working with versions above v2.5.0 😃  /cc @bnferguson ❤️

**Comment by bnferguson** [comment]
@meatballhat - Helloooooo! when we had those few versions we had to yank because they were broken some customers rolled back to 2.5.0 which was the last working version at that time. The newest one works, but has a new issue of causing builds to not be picked up in 2.6.1. Seems that the  `export TRAVIS_ENTERPRISE_BUILD_ENDPOINT="__build__"` line gets commented out in installations upon upgrade. Weirdly, from what we can tell, this has been the case for about 1.5 years but only in 2.9.2 has it started causing problems (and mostly with 2.6.1 it seems? Maybe something changed in `travis-build`?). 

We have an internal tracking issue at https://github.com/travis-pro/team-cyan/issues/3 (sorry for the private link ya'll). 

Once it's uncommented it starts working again, so it's safe to use with that work around. Haven't had a chance to dig into things to figure out what changed or what's breaking because of other pressing issues customers are having.

**Comment by amanya** [comment]
As @bnferguson created a separated issue for that I'm closing this one. Thanks! :)
